#Kevin Beaghan  2/7/2025
#Lab A Week 3 - Using turtle to draw first and last initials in different colors

import turtle

wn=turtle.Screen()
wn.bgcolor("lightgrey")

initial=turtle.Turtle()
initial.pencolor("green")
initial.fillcolor("lightgreen")
initial.pensize(5)

initial.begin_fill()
initial.left(90)
initial.forward(200)
initial.right(90)
initial.forward(10)
initial.right(90)
initial.forward(90)
initial.left(135)
initial.forward(130)
initial.right(90)
initial.forward(10)
initial.right(90)
initial.forward(130)
initial.left(90)
initial.forward(130)
initial.right(90)
initial.forward(10)
initial.right(90)
initial.forward(130)
initial.left(135)
initial.forward(100)
initial.right(90)
initial.forward(10)
initial.end_fill()

initial.up()
initial.pencolor("blue")
initial.fillcolor("lightblue")
initial.right(180)
initial.forward(150)
initial.down()

initial.begin_fill()
initial.left(90)
initial.forward(200)
initial.right(120)
initial.forward(100)
initial.right(100)
initial.forward(70)
initial.left(90)
initial.forward(70)
initial.right(110)
initial.forward(111)
initial.end_fill()

turtle.done()